log:
  level: INFO
api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true
#   middlewares:
    #    redirect-to-https:
    #      redirectScheme:
    #        scheme: https
    #        permanent: false
  https:
    address: ":443"
    forwardedHeaders:
      insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsEncrypt:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: acme.json
      email: admin@t4s.pro
      httpChallenge:
        entryPoint: http